Part 1: Data Cleaning (Titanic Dataset)

In [34]:
import matplotlib.pyplot as plt
import random
import numpy as np
import pandas as pd
from sklearn import datasets, svm, cross_validation, tree, preprocessing, metrics
import sklearn.ensemble as ske
#import tensorflow as tf
#from tensorflow.contrib import skflow
df = pd.read_excel('titanic3.xls', 'titanic3', index_col=None, na_values=['NA'])
df.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"

In [13]:
df.tail()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
1304,3,0,"Zabour, Miss. Hileni",female,14.5,1,0,2665,14.4542,NaN,C,NaN,328.0,NaN
1305,3,0,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,NaN,NaN,NaN
1306,3,0,"Zakarian, Mr. Mapriededer",male,26.5,0,0,2656,7.2250,NaN,C,NaN,304.0,NaN
1307,3,0,"Zakarian, Mr. Ortin",male,27.0,0,0,2670,7.2250,NaN,C,NaN,NaN,NaN
1308,3,0,"Zimmerman, Mr. Leo",male,29.0,0,0,315082,7.8750,NaN,S,NaN,NaN,NaN

In [14]:
df.columns

Index(['pclass', 'survived', 'name', 'sex', 'age', 'sibsp', 'parch', 'ticket',
       'fare', 'cabin', 'embarked', 'boat', 'body', 'home.dest'],
      dtype='object')

In [15]:
df.shape

(1309, 14)

In [16]:
df.isnull()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,False,False,False,False,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False,False,False,True,False
2,False,False,False,False,False,False,False,False,False,False,False,True,True,False
3,False,False,False,False,False,False,False,False,False,False,False,True,False,False
4,False,False,False,False,False,False,False,False,False,False,False,True,True,False
5,False,False,False,False,False,False,False,False,False,False,False,False,True,False
6,False,False,False,False,False,False,False,False,False,False,False,False,True,False
7,False,False,False,False,False,False,False,False,False,False,False,True,True,False
8,False,False,False,False,False,False,False,False,False,False,False,False,True,False
9,False,False,False,False,False,False,False,False,False,True,False,True,False,False
10,False,False,False,False,False,False,False,False,False,False,False,True,False,False
11,False,False,False,False,False,False,False,False,False,False,False,False,True,False
12,False,False,False,False,False,False,False,False,False,False,False,False,True,False
13,False,False,False,False,False,False,False,False,False,True,False,False,True,True
14,False,False,False,False,False,False,False,False,False,False,False,False,True,False
15,False,False,False,False,True,False,False,False,False,True,False,True,True,False
16,False,False,False,False,False,False,False,False,False,False,False,True,True,False
17,False,False,False,False,False,False,False,False,False,False,False,False,True,False
18,False,False,False,False,False,False,False,False,False,False,False,False,True,True
19,False,False,False,False,False,False,False,False,False,False,False,False,True,False
20,False,False,False,False,False,False,False,False,False,False,False,False,True,False
21,False,False,False,False,False,False,False,False,False,False,False,False,True,False
22,False,False,False,False,False,False,False,False,False,False,False,False,True,False
23,False,False,False,False,False,False,False,False,False,True,False,False,True,True
24,False,False,False,False,False,False,False,False,False,False,False,False,True,True
25,False,False,False,False,False,False,False,False,False,True,False,True,False,False
26,False,False,False,False,False,False,False,False,False,False,False,False,True,False
27,False,False,False,False,False,False,False,False,False,False,False,False,True,False
28,False,False,False,False,False,False,False,False,False,False,False,False,True,True
29,False,False,False,False,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1279,False,False,False,False,False,False,False,False,False,True,False,True,True,True
1280,False,False,False,False,False,False,False,False,False,True,False,True,True,True
1281,False,False,False,False,False,False,False,False,False,True,False,True,True,False
1282,False,False,False,False,True,False,False,False,False,True,False,True,True,True
1283,False,False,False,False,True,False,False,False,False,True,False,True,True,True
1284,False,False,False,False,True,False,False,False,False,True,False,True,True,True
1285,False,False,False,False,False,False,False,False,False,True,False,True,False,True
1286,False,False,False,False,False,False,False,False,False,True,False,False,True,True
1287,False,False,False,False,False,False,False,False,False,True,False,True,True,True
1288,False,False,False,False,False,False,False,False,False,True,False,True,False,True
1289,False,False,False,False,False,False,False,False,False,True,False,True,True,True
1290,False,False,False,False,False,False,False,False,False,True,False,True,True,True
1291,False,False,False,False,True,False,False,False,False,True,False,True,True,True
1292,False,False,False,False,True,False,False,False,False,True,False,True,True,True
1293,False,False,False,False,True,False,False,False,False,True,False,True,True,True
1294,False,False,False,False,False,False,False,False,False,True,False,True,False,True
1295,False,False,False,False,False,False,False,False,False,True,False,True,True,True
1296,False,False,False,False,False,False,False,False,False,True,False,True,False,True
1297,False,False,False,False,True,False,False,False,False,True,False,True,True,True
1298,False,False,False,False,False,False,False,False,False,True,False,True,True,True
1299,False,False,False,False,False,False,False,False,False,True,False,False,True,True
1300,False,False,False,False,False,False,False,False,False,True,False,True,True,True
1301,False,False,False,False,False,False,False,False,False,True,False,True,False,True
1302,False,False,False,False,True,False,False,False,False,True,False,True,True,True
1303,False,False,False,False,True,False,False,False,False,True,False,True,True,True
1304,False,False,False,False,False,False,False,False,False,True,False,True,False,True
1305,False,False,False,False,True,False,False,False,False,True,False,True,True,True
1306,False,False,False,False,False,False,False,False,False,True,False,True,False,True
1307,False,False,False,False,False,False,False,False,False,True,False,True,True,True
1308,False,False,False,False,False,False,False,False,False,True,False,True,True,True

In [32]:
#replace all NaN values (which are showing up as 'True' in pandas) with 'None'
df = df.astype(object).where(pd.notnull(df),None)

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,False,False,False,False,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False,False,False,True,False
2,False,False,False,False,False,False,False,False,False,False,False,True,True,False
3,False,False,False,False,False,False,False,False,False,False,False,True,False,False
4,False,False,False,False,False,False,False,False,False,False,False,True,True,False
5,False,False,False,False,False,False,False,False,False,False,False,False,True,False
6,False,False,False,False,False,False,False,False,False,False,False,False,True,False
7,False,False,False,False,False,False,False,False,False,False,False,True,True,False
8,False,False,False,False,False,False,False,False,False,False,False,False,True,False
9,False,False,False,False,False,False,False,False,False,True,False,True,False,False
10,False,False,False,False,False,False,False,False,False,False,False,True,False,False
11,False,False,False,False,False,False,False,False,False,False,False,False,True,False
12,False,False,False,False,False,False,False,False,False,False,False,False,True,False
13,False,False,False,False,False,False,False,False,False,True,False,False,True,True
14,False,False,False,False,False,False,False,False,False,False,False,False,True,False
15,False,False,False,False,True,False,False,False,False,True,False,True,True,False
16,False,False,False,False,False,False,False,False,False,False,False,True,True,False
17,False,False,False,False,False,False,False,False,False,False,False,False,True,False
18,False,False,False,False,False,False,False,False,False,False,False,False,True,True
19,False,False,False,False,False,False,False,False,False,False,False,False,True,False
20,False,False,False,False,False,False,False,False,False,False,False,False,True,False
21,False,False,False,False,False,False,False,False,False,False,False,False,True,False
22,False,False,False,False,False,False,False,False,False,False,False,False,True,False
23,False,False,False,False,False,False,False,False,False,True,False,False,True,True
24,False,False,False,False,False,False,False,False,False,False,False,False,True,True
25,False,False,False,False,False,False,False,False,False,True,False,True,False,False
26,False,False,False,False,False,False,False,False,False,False,False,False,True,False
27,False,False,False,False,False,False,False,False,False,False,False,False,True,False
28,False,False,False,False,False,False,False,False,False,False,False,False,True,True
29,False,False,False,False,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1279,False,False,False,False,False,False,False,False,False,True,False,True,True,True
1280,False,False,False,False,False,False,False,False,False,True,False,True,True,True
1281,False,False,False,False,False,False,False,False,False,True,False,True,True,False
1282,False,False,False,False,True,False,False,False,False,True,False,True,True,True
1283,False,False,False,False,True,False,False,False,False,True,False,True,True,True
1284,False,False,False,False,True,False,False,False,False,True,False,True,True,True
1285,False,False,False,False,False,False,False,False,False,True,False,True,False,True
1286,False,False,False,False,False,False,False,False,False,True,False,False,True,True
1287,False,False,False,False,False,False,False,False,False,True,False,True,True,True
1288,False,False,False,False,False,False,False,False,False,True,False,True,False,True
1289,False,False,False,False,False,False,False,False,False,True,False,True,True,True
1290,False,False,False,False,False,False,False,False,False,True,False,True,True,True
1291,False,False,False,False,True,False,False,False,False,True,False,True,True,True
1292,False,False,False,False,True,False,False,False,False,True,False,True,True,True
1293,False,False,False,False,True,False,False,False,False,True,False,True,True,True
1294,False,False,False,False,False,False,False,False,False,True,False,True,False,True
1295,False,False,False,False,False,False,False,False,False,True,False,True,True,True
1296,False,False,False,False,False,False,False,False,False,True,False,True,False,True
1297,False,False,False,False,True,False,False,False,False,True,False,True,True,True
1298,False,False,False,False,False,False,False,False,False,True,False,True,True,True
1299,False,False,False,False,False,False,False,False,False,True,False,False,True,True
1300,False,False,False,False,False,False,False,False,False,True,False,True,True,True
1301,False,False,False,False,False,False,False,False,False,True,False,True,False,True
1302,False,False,False,False,True,False,False,False,False,True,False,True,True,True
1303,False,False,False,False,True,False,False,False,False,True,False,True,True,True
1304,False,False,False,False,False,False,False,False,False,True,False,True,False,True
1305,False,False,False,False,True,False,False,False,False,True,False,True,True,True
1306,False,False,False,False,False,False,False,False,False,True,False,True,False,True
1307,False,False,False,False,False,False,False,False,False,True,False,True,True,True
1308,False,False,False,False,False,False,False,False,False,True,False,True,True,True

In [33]:
k = 0.2
from sklearn.model_selection import train_test_split
train, test = train_test_split(df, test_size = k)

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,False,False,False,False,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False,False,False,True,False
2,False,False,False,False,False,False,False,False,False,False,False,True,True,False
3,False,False,False,False,False,False,False,False,False,False,False,True,False,False
4,False,False,False,False,False,False,False,False,False,False,False,True,True,False
5,False,False,False,False,False,False,False,False,False,False,False,False,True,False
6,False,False,False,False,False,False,False,False,False,False,False,False,True,False
7,False,False,False,False,False,False,False,False,False,False,False,True,True,False
8,False,False,False,False,False,False,False,False,False,False,False,False,True,False
9,False,False,False,False,False,False,False,False,False,True,False,True,False,False
10,False,False,False,False,False,False,False,False,False,False,False,True,False,False
11,False,False,False,False,False,False,False,False,False,False,False,False,True,False
12,False,False,False,False,False,False,False,False,False,False,False,False,True,False
13,False,False,False,False,False,False,False,False,False,True,False,False,True,True
14,False,False,False,False,False,False,False,False,False,False,False,False,True,False
15,False,False,False,False,True,False,False,False,False,True,False,True,True,False
16,False,False,False,False,False,False,False,False,False,False,False,True,True,False
17,False,False,False,False,False,False,False,False,False,False,False,False,True,False
18,False,False,False,False,False,False,False,False,False,False,False,False,True,True
19,False,False,False,False,False,False,False,False,False,False,False,False,True,False
20,False,False,False,False,False,False,False,False,False,False,False,False,True,False
21,False,False,False,False,False,False,False,False,False,False,False,False,True,False
22,False,False,False,False,False,False,False,False,False,False,False,False,True,False
23,False,False,False,False,False,False,False,False,False,True,False,False,True,True
24,False,False,False,False,False,False,False,False,False,False,False,False,True,True
25,False,False,False,False,False,False,False,False,False,True,False,True,False,False
26,False,False,False,False,False,False,False,False,False,False,False,False,True,False
27,False,False,False,False,False,False,False,False,False,False,False,False,True,False
28,False,False,False,False,False,False,False,False,False,False,False,False,True,True
29,False,False,False,False,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1279,False,False,False,False,False,False,False,False,False,True,False,True,True,True
1280,False,False,False,False,False,False,False,False,False,True,False,True,True,True
1281,False,False,False,False,False,False,False,False,False,True,False,True,True,False
1282,False,False,False,False,True,False,False,False,False,True,False,True,True,True
1283,False,False,False,False,True,False,False,False,False,True,False,True,True,True
1284,False,False,False,False,True,False,False,False,False,True,False,True,True,True
1285,False,False,False,False,False,False,False,False,False,True,False,True,False,True
1286,False,False,False,False,False,False,False,False,False,True,False,False,True,True
1287,False,False,False,False,False,False,False,False,False,True,False,True,True,True
1288,False,False,False,False,False,False,False,False,False,True,False,True,False,True
1289,False,False,False,False,False,False,False,False,False,True,False,True,True,True
1290,False,False,False,False,False,False,False,False,False,True,False,True,True,True
1291,False,False,False,False,True,False,False,False,False,True,False,True,True,True
1292,False,False,False,False,True,False,False,False,False,True,False,True,True,True
1293,False,False,False,False,True,False,False,False,False,True,False,True,True,True
1294,False,False,False,False,False,False,False,False,False,True,False,True,False,True
1295,False,False,False,False,False,False,False,False,False,True,False,True,True,True
1296,False,False,False,False,False,False,False,False,False,True,False,True,False,True
1297,False,False,False,False,True,False,False,False,False,True,False,True,True,True
1298,False,False,False,False,False,False,False,False,False,True,False,True,True,True
1299,False,False,False,False,False,False,False,False,False,True,False,False,True,True
1300,False,False,False,False,False,False,False,False,False,True,False,True,True,True
1301,False,False,False,False,False,False,False,False,False,True,False,True,False,True
1302,False,False,False,False,True,False,False,False,False,True,False,True,True,True
1303,False,False,False,False,True,False,False,False,False,True,False,True,True,True
1304,False,False,False,False,False,False,False,False,False,True,False,True,False,True
1305,False,False,False,False,True,False,False,False,False,True,False,True,True,True
1306,False,False,False,False,False,False,False,False,False,True,False,True,False,True
1307,False,False,False,False,False,False,False,False,False,True,False,True,True,True
1308,False,False,False,False,False,False,False,False,False,True,False,True,True,True

In [28]:
train.head(10)

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
308,1,1,"White, Mrs. John Stuart (Ella Holmes)",female,55,0,0,PC 17760,135.633,C32,C,8,None,"New York, NY / Briarcliff Manor NY"
600,3,0,"Abbing, Mr. Anthony",male,42,0,0,C.A. 5547,7.55,None,S,None,None,None
712,3,0,"Celotti, Mr. Francesco",male,24,0,0,343275,8.05,None,S,None,None,London
67,1,1,"Cherry, Miss. Gladys",female,30,0,0,110152,86.5,B77,S,8,None,"London, England"
860,3,1,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.925,None,S,None,None,None
504,2,0,"Meyer, Mr. August",male,39,0,0,248723,13,None,S,None,None,"Harrow-on-the-Hill, Middlesex"
1204,3,0,"Sivola, Mr. Antti Wilhelm",male,21,0,0,STON/O 2. 3101280,7.925,None,S,None,None,None
760,3,1,"de Mulder, Mr. Theodore",male,30,0,0,345774,9.5,None,S,11,None,"Belgium Detroit, MI"
84,1,0,"Cumings, Mr. John Bradley",male,39,1,0,PC 17599,71.2833,C85,C,None,None,"New York, NY"
597,2,1,"Williams, Mr. Charles Eugene",male,None,0,0,244373,13,None,S,14,None,"Harrow, England"

In [29]:
test.head(10)

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
1098,3,0,"Palsson, Miss. Stina Viola",female,3,3,1,349909,21.075,None,S,None,None,None
1017,3,1,"Midtsjo, Mr. Karl Albert",male,21,0,0,345501,7.775,None,S,15,None,None
275,1,1,"Spedden, Mrs. Frederic Oakley (Margaretta Corn...",female,40,1,1,16966,134.5,E34,C,3,None,"Tuxedo Park, NY"
266,1,0,"Smart, Mr. John Montgomery",male,56,0,0,113792,26.55,None,S,None,None,"New York, NY"
1074,3,0,"O'Connor, Mr. Patrick",male,None,0,0,366713,7.75,None,Q,None,None,None
1172,3,0,"Sage, Miss. Ada",female,None,8,2,CA. 2343,69.55,None,S,None,None,None
465,2,1,"Jerwan, Mrs. Amin S (Marie Marthe Thuillard)",female,23,0,0,SC/AH Basle 541,13.7917,D,C,11,None,"New York, NY"
1075,3,0,"Odahl, Mr. Nils Martin",male,23,0,0,7267,9.225,None,S,None,None,None
46,1,0,"Cairns, Mr. Alexander",male,None,0,0,113798,31,None,S,None,None,None
1301,3,0,"Youseff, Mr. Gerious",male,45.5,0,0,2628,7.225,None,C,None,312,None